# Generated by Django 5.0.1 on 2024-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(upload_to='')),
                ('date_of_join', models.DateField(verbose_name='Date of Joining')),
            ],
        ),
    ]
