# Generated by Django 5.0.7 on 2024-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30, null=True)),
                ('store_description', models.CharField(max_length=100)),
                ('store_logo', models.ImageField(upload_to='')),
                ('store_creation_date', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_join',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Joining'),
        ),
    ]
