# Generated by Django 5.0.7 on 2024-09-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_stores_alter_user_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='home_page.user'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_logo',
            field=models.ImageField(upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
